/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PaymentLinkRequestReferenceDataListInner
    /// </summary>
    [DataContract(Name = "PaymentLinkRequest_referenceDataList_inner")]
    public partial class PaymentLinkRequestReferenceDataListInner : IValidatableObject
    {
        /// <summary>
        /// Defines ReferenceType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReferenceTypeEnum
        {
            /// <summary>
            /// Enum QuoteId for value: QuoteId
            /// </summary>
            [EnumMember(Value = "QuoteId")]
            QuoteId = 1,

            /// <summary>
            /// Enum AccountNumber for value: AccountNumber
            /// </summary>
            [EnumMember(Value = "AccountNumber")]
            AccountNumber = 2,

            /// <summary>
            /// Enum PolicyNumber for value: PolicyNumber
            /// </summary>
            [EnumMember(Value = "PolicyNumber")]
            PolicyNumber = 3,

            /// <summary>
            /// Enum InvoiceNumber for value: InvoiceNumber
            /// </summary>
            [EnumMember(Value = "InvoiceNumber")]
            InvoiceNumber = 4,

            /// <summary>
            /// Enum Other for value: Other
            /// </summary>
            [EnumMember(Value = "Other")]
            Other = 5
        }


        /// <summary>
        /// Gets or Sets ReferenceType
        /// </summary>
        [DataMember(Name = "referenceType", IsRequired = true, EmitDefaultValue = true)]
        public ReferenceTypeEnum ReferenceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentLinkRequestReferenceDataListInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentLinkRequestReferenceDataListInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentLinkRequestReferenceDataListInner" /> class.
        /// </summary>
        /// <param name="referenceType">referenceType (required).</param>
        /// <param name="referenceNumber">referenceNumber (required).</param>
        /// <param name="referenceKey">referenceKey.</param>
        public PaymentLinkRequestReferenceDataListInner(ReferenceTypeEnum referenceType = default(ReferenceTypeEnum), string referenceNumber = default(string), string referenceKey = default(string))
        {
            this.ReferenceType = referenceType;
            // to ensure "referenceNumber" is required (not null)
            if (referenceNumber == null)
            {
                throw new ArgumentNullException("referenceNumber is a required property for PaymentLinkRequestReferenceDataListInner and cannot be null");
            }
            this.ReferenceNumber = referenceNumber;
            this.ReferenceKey = referenceKey;
        }

        /// <summary>
        /// Gets or Sets ReferenceNumber
        /// </summary>
        [DataMember(Name = "referenceNumber", IsRequired = true, EmitDefaultValue = true)]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceKey
        /// </summary>
        [DataMember(Name = "referenceKey", EmitDefaultValue = false)]
        public string ReferenceKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentLinkRequestReferenceDataListInner {\n");
            sb.Append("  ReferenceType: ").Append(ReferenceType).Append("\n");
            sb.Append("  ReferenceNumber: ").Append(ReferenceNumber).Append("\n");
            sb.Append("  ReferenceKey: ").Append(ReferenceKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
