/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SecureVerifyBankAccountRequestDTO
    /// </summary>
    [DataContract(Name = "SecureVerifyBankAccountRequestDTO")]
    public partial class SecureVerifyBankAccountRequestDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SecureVerifyBankAccountRequestDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SecureVerifyBankAccountRequestDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SecureVerifyBankAccountRequestDTO" /> class.
        /// </summary>
        /// <param name="verificationEntityId">verificationEntityId.</param>
        /// <param name="accountNumber">accountNumber (required).</param>
        /// <param name="routingNumber">routingNumber (required).</param>
        /// <param name="accountHolderName">accountHolderName.</param>
        /// <param name="explicitVerification">explicitVerification.</param>
        public SecureVerifyBankAccountRequestDTO(string verificationEntityId = default(string), string accountNumber = default(string), string routingNumber = default(string), string accountHolderName = default(string), bool explicitVerification = default(bool))
        {
            // to ensure "accountNumber" is required (not null)
            if (accountNumber == null)
            {
                throw new ArgumentNullException("accountNumber is a required property for SecureVerifyBankAccountRequestDTO and cannot be null");
            }
            this.AccountNumber = accountNumber;
            // to ensure "routingNumber" is required (not null)
            if (routingNumber == null)
            {
                throw new ArgumentNullException("routingNumber is a required property for SecureVerifyBankAccountRequestDTO and cannot be null");
            }
            this.RoutingNumber = routingNumber;
            this.VerificationEntityId = verificationEntityId;
            this.AccountHolderName = accountHolderName;
            this.ExplicitVerification = explicitVerification;
        }

        /// <summary>
        /// Gets or Sets VerificationEntityId
        /// </summary>
        [DataMember(Name = "verificationEntityId", EmitDefaultValue = false)]
        public string VerificationEntityId { get; set; }

        /// <summary>
        /// Gets or Sets AccountNumber
        /// </summary>
        [DataMember(Name = "accountNumber", IsRequired = true, EmitDefaultValue = true)]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Gets or Sets RoutingNumber
        /// </summary>
        [DataMember(Name = "routingNumber", IsRequired = true, EmitDefaultValue = true)]
        public string RoutingNumber { get; set; }

        /// <summary>
        /// Gets or Sets AccountHolderName
        /// </summary>
        [DataMember(Name = "accountHolderName", EmitDefaultValue = false)]
        public string AccountHolderName { get; set; }

        /// <summary>
        /// Gets or Sets ExplicitVerification
        /// </summary>
        [DataMember(Name = "explicitVerification", EmitDefaultValue = true)]
        public bool ExplicitVerification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SecureVerifyBankAccountRequestDTO {\n");
            sb.Append("  VerificationEntityId: ").Append(VerificationEntityId).Append("\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("  RoutingNumber: ").Append(RoutingNumber).Append("\n");
            sb.Append("  AccountHolderName: ").Append(AccountHolderName).Append("\n");
            sb.Append("  ExplicitVerification: ").Append(ExplicitVerification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
