/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TransactionPaymentResponseAchTenderInfoCommissionType
    /// </summary>
    [JsonConverter(typeof(TransactionPaymentResponseAchTenderInfoCommissionTypeJsonConverter))]
    [DataContract(Name = "TransactionPaymentResponse_achTenderInfo_commissionType")]
    public partial class TransactionPaymentResponseAchTenderInfoCommissionType : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionPaymentResponseAchTenderInfoCommissionType" /> class
        /// with the <see cref="int" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of int.</param>
        public TransactionPaymentResponseAchTenderInfoCommissionType(int actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionPaymentResponseAchTenderInfoCommissionType" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public TransactionPaymentResponseAchTenderInfoCommissionType(string actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(int) || value is int)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(string) || value is string)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: int, string");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `int`. If the actual instance is not `int`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of int</returns>
        public int GetInt()
        {
            return (int)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `string`. If the actual instance is not `string`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionPaymentResponseAchTenderInfoCommissionType {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, TransactionPaymentResponseAchTenderInfoCommissionType.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of TransactionPaymentResponseAchTenderInfoCommissionType
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of TransactionPaymentResponseAchTenderInfoCommissionType</returns>
        public static TransactionPaymentResponseAchTenderInfoCommissionType FromJson(string jsonString)
        {
            TransactionPaymentResponseAchTenderInfoCommissionType newTransactionPaymentResponseAchTenderInfoCommissionType = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newTransactionPaymentResponseAchTenderInfoCommissionType;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(int).GetProperty("AdditionalProperties") == null)
                {
                    newTransactionPaymentResponseAchTenderInfoCommissionType = new TransactionPaymentResponseAchTenderInfoCommissionType(JsonConvert.DeserializeObject<int>(jsonString, TransactionPaymentResponseAchTenderInfoCommissionType.SerializerSettings));
                }
                else
                {
                    newTransactionPaymentResponseAchTenderInfoCommissionType = new TransactionPaymentResponseAchTenderInfoCommissionType(JsonConvert.DeserializeObject<int>(jsonString, TransactionPaymentResponseAchTenderInfoCommissionType.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("int");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into int: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(string).GetProperty("AdditionalProperties") == null)
                {
                    newTransactionPaymentResponseAchTenderInfoCommissionType = new TransactionPaymentResponseAchTenderInfoCommissionType(JsonConvert.DeserializeObject<string>(jsonString, TransactionPaymentResponseAchTenderInfoCommissionType.SerializerSettings));
                }
                else
                {
                    newTransactionPaymentResponseAchTenderInfoCommissionType = new TransactionPaymentResponseAchTenderInfoCommissionType(JsonConvert.DeserializeObject<string>(jsonString, TransactionPaymentResponseAchTenderInfoCommissionType.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("string");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into string: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newTransactionPaymentResponseAchTenderInfoCommissionType;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for TransactionPaymentResponseAchTenderInfoCommissionType
    /// </summary>
    public class TransactionPaymentResponseAchTenderInfoCommissionTypeJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(TransactionPaymentResponseAchTenderInfoCommissionType).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.Integer: 
                    return new TransactionPaymentResponseAchTenderInfoCommissionType(Convert.ToInt32(reader.Value));
                case JsonToken.String: 
                    return new TransactionPaymentResponseAchTenderInfoCommissionType(Convert.ToString(reader.Value));
                case JsonToken.StartObject:
                    return TransactionPaymentResponseAchTenderInfoCommissionType.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return TransactionPaymentResponseAchTenderInfoCommissionType.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
