/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SecureACHValidationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecureACHValidationApiTests : IDisposable
    {
        private SecureACHValidationApi instance;

        public SecureACHValidationApiTests()
        {
            instance = new SecureACHValidationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureACHValidationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecureACHValidationApi
            //Assert.IsType<SecureACHValidationApi>(instance);
        }

        /// <summary>
        /// Test UtilityapiSecureVerifybankaccountsPost
        /// </summary>
        [Fact]
        public void UtilityapiSecureVerifybankaccountsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO = null;
            //var response = instance.UtilityapiSecureVerifybankaccountsPost(xApiKey, xAppKey, xVersion, origin, secureVerifyBankAccountRequestDTO);
            //Assert.IsType<VerifyBankAccountResponse>(response);
        }
    }
}
