/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SecureAutopayEnrollmentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecureAutopayEnrollmentApiTests : IDisposable
    {
        private SecureAutopayEnrollmentApi instance;

        public SecureAutopayEnrollmentApiTests()
        {
            instance = new SecureAutopayEnrollmentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureAutopayEnrollmentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecureAutopayEnrollmentApi
            //Assert.IsType<SecureAutopayEnrollmentApi>(instance);
        }

        /// <summary>
        /// Test SecureAutopayenrollmentPost
        /// </summary>
        [Fact]
        public void SecureAutopayenrollmentPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //AutoPayEnrollmentRequest autoPayEnrollmentRequest = null;
            //var response = instance.SecureAutopayenrollmentPost(xApiKey, xAppKey, xVersion, origin, autoPayEnrollmentRequest);
            //Assert.IsType<AutoPayEnrollmentResponse>(response);
        }
    }
}
