/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using AndDoneSecureClientLibrary.Client;
using AndDoneSecureClientLibrary.Model;

namespace AndDoneSecureClientLibrary.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureReportsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// This API will add system report.
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void SecureReportsDownloadsPost(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0);

        /// <summary>
        /// This API will add system report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SecureReportsDownloadsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureReportsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// This API will add system report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SecureReportsDownloadsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API will add system report.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SecureReportsDownloadsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureReportsApi : ISecureReportsApiSync, ISecureReportsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SecureReportsApi : ISecureReportsApi
    {
        private AndDoneSecureClientLibrary.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureReportsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecureReportsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureReportsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecureReportsApi(string basePath)
        {
            this.Configuration = AndDoneSecureClientLibrary.Client.Configuration.MergeConfigurations(
                AndDoneSecureClientLibrary.Client.GlobalConfiguration.Instance,
                new AndDoneSecureClientLibrary.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureReportsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SecureReportsApi(AndDoneSecureClientLibrary.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AndDoneSecureClientLibrary.Client.Configuration.MergeConfigurations(
                AndDoneSecureClientLibrary.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureReportsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SecureReportsApi(AndDoneSecureClientLibrary.Client.ISynchronousClient client, AndDoneSecureClientLibrary.Client.IAsynchronousClient asyncClient, AndDoneSecureClientLibrary.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AndDoneSecureClientLibrary.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// This API will add system report. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void SecureReportsDownloadsPost(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0)
        {
            SecureReportsDownloadsPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, reportDownloadRequest);
        }

        /// <summary>
        /// This API will add system report. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AndDoneSecureClientLibrary.Client.ApiResponse<Object> SecureReportsDownloadsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureReportsApi->SecureReportsDownloadsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureReportsApi->SecureReportsDownloadsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureReportsApi->SecureReportsDownloadsPost");
            }

            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/csv"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = reportDownloadRequest;

            localVarRequestOptions.Operation = "SecureReportsApi.SecureReportsDownloadsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/secure/reports/downloads", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureReportsDownloadsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API will add system report. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SecureReportsDownloadsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await SecureReportsDownloadsPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, reportDownloadRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// This API will add system report. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="reportDownloadRequest">ReportDownloadRequest (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AndDoneSecureClientLibrary.Client.ApiResponse<Object>> SecureReportsDownloadsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, ReportDownloadRequest reportDownloadRequest = default(ReportDownloadRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureReportsApi->SecureReportsDownloadsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureReportsApi->SecureReportsDownloadsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureReportsApi->SecureReportsDownloadsPost");
            }


            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/csv"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = reportDownloadRequest;

            localVarRequestOptions.Operation = "SecureReportsApi.SecureReportsDownloadsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/secure/reports/downloads", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureReportsDownloadsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
