/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using AndDoneSecureClientLibrary.Client;
using AndDoneSecureClientLibrary.Model;

namespace AndDoneSecureClientLibrary.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecurePaymentLinksApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkResponse</returns>
        PaymentLinkResponse SecurePaymentlinksDetailsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0);

        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkResponse</returns>
        ApiResponse<PaymentLinkResponse> SecurePaymentlinksDetailsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0);
        /// <summary>
        /// This API is used for to set expired payment link
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkExpiresResponse</returns>
        PaymentLinkExpiresResponse SecurePaymentlinksExpirationsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0);

        /// <summary>
        /// This API is used for to set expired payment link
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkExpiresResponse</returns>
        ApiResponse<PaymentLinkExpiresResponse> SecurePaymentlinksExpirationsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0);
        /// <summary>
        /// This API is used to update Payment Links
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkResponse</returns>
        PaymentLinkResponse SecurePaymentlinksIdPut(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0);

        /// <summary>
        /// This API is used to update Payment Links
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkResponse</returns>
        ApiResponse<PaymentLinkResponse> SecurePaymentlinksIdPutWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0);
        /// <summary>
        /// This API is used to create Payment Links
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkResponse</returns>
        PaymentLinkResponse SecurePaymentlinksPost(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0);

        /// <summary>
        /// This API is used to create Payment Links
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkResponse</returns>
        ApiResponse<PaymentLinkResponse> SecurePaymentlinksPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecurePaymentLinksApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkResponse</returns>
        System.Threading.Tasks.Task<PaymentLinkResponse> SecurePaymentlinksDetailsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentLinkResponse>> SecurePaymentlinksDetailsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API is used for to set expired payment link
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkExpiresResponse</returns>
        System.Threading.Tasks.Task<PaymentLinkExpiresResponse> SecurePaymentlinksExpirationsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used for to set expired payment link
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkExpiresResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentLinkExpiresResponse>> SecurePaymentlinksExpirationsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API is used to update Payment Links
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkResponse</returns>
        System.Threading.Tasks.Task<PaymentLinkResponse> SecurePaymentlinksIdPutAsync(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used to update Payment Links
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentLinkResponse>> SecurePaymentlinksIdPutWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API is used to create Payment Links
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkResponse</returns>
        System.Threading.Tasks.Task<PaymentLinkResponse> SecurePaymentlinksPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used to create Payment Links
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentLinkResponse>> SecurePaymentlinksPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecurePaymentLinksApi : ISecurePaymentLinksApiSync, ISecurePaymentLinksApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SecurePaymentLinksApi : ISecurePaymentLinksApi
    {
        private AndDoneSecureClientLibrary.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentLinksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecurePaymentLinksApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentLinksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecurePaymentLinksApi(string basePath)
        {
            this.Configuration = AndDoneSecureClientLibrary.Client.Configuration.MergeConfigurations(
                AndDoneSecureClientLibrary.Client.GlobalConfiguration.Instance,
                new AndDoneSecureClientLibrary.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentLinksApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SecurePaymentLinksApi(AndDoneSecureClientLibrary.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AndDoneSecureClientLibrary.Client.Configuration.MergeConfigurations(
                AndDoneSecureClientLibrary.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurePaymentLinksApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SecurePaymentLinksApi(AndDoneSecureClientLibrary.Client.ISynchronousClient client, AndDoneSecureClientLibrary.Client.IAsynchronousClient asyncClient, AndDoneSecureClientLibrary.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AndDoneSecureClientLibrary.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkResponse</returns>
        public PaymentLinkResponse SecurePaymentlinksDetailsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0)
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> localVarResponse = SecurePaymentlinksDetailsPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, securePaymentLinkRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkResponse</returns>
        public AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> SecurePaymentlinksDetailsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }

            // verify the required parameter 'securePaymentLinkRequest' is set
            if (securePaymentLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'securePaymentLinkRequest' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }

            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksDetailsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<PaymentLinkResponse>("/secure/paymentlinks/details", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksDetailsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkResponse</returns>
        public async System.Threading.Tasks.Task<PaymentLinkResponse> SecurePaymentlinksDetailsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> localVarResponse = await SecurePaymentlinksDetailsPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, securePaymentLinkRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting Payment Links by PaymentLink ID 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkResponse)</returns>
        public async System.Threading.Tasks.Task<AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse>> SecurePaymentlinksDetailsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }

            // verify the required parameter 'securePaymentLinkRequest' is set
            if (securePaymentLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'securePaymentLinkRequest' when calling SecurePaymentLinksApi->SecurePaymentlinksDetailsPost");
            }


            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksDetailsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PaymentLinkResponse>("/secure/paymentlinks/details", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksDetailsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for to set expired payment link 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkExpiresResponse</returns>
        public PaymentLinkExpiresResponse SecurePaymentlinksExpirationsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0)
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkExpiresResponse> localVarResponse = SecurePaymentlinksExpirationsPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, securePaymentLinkRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for to set expired payment link 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkExpiresResponse</returns>
        public AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkExpiresResponse> SecurePaymentlinksExpirationsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksExpirationsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksExpirationsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksExpirationsPost");
            }

            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksExpirationsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<PaymentLinkExpiresResponse>("/secure/paymentlinks/expirations", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksExpirationsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for to set expired payment link 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkExpiresResponse</returns>
        public async System.Threading.Tasks.Task<PaymentLinkExpiresResponse> SecurePaymentlinksExpirationsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkExpiresResponse> localVarResponse = await SecurePaymentlinksExpirationsPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, securePaymentLinkRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for to set expired payment link 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="securePaymentLinkRequest">Secure Payment Link Request (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkExpiresResponse)</returns>
        public async System.Threading.Tasks.Task<AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkExpiresResponse>> SecurePaymentlinksExpirationsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecurePaymentLinkRequest securePaymentLinkRequest = default(SecurePaymentLinkRequest), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksExpirationsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksExpirationsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksExpirationsPost");
            }


            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = securePaymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksExpirationsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PaymentLinkExpiresResponse>("/secure/paymentlinks/expirations", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksExpirationsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used to update Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkResponse</returns>
        public PaymentLinkResponse SecurePaymentlinksIdPut(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0)
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> localVarResponse = SecurePaymentlinksIdPutWithHttpInfo(xApiKey, xAppKey, xVersion, origin, id, secureUpdatePaymentLinkRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used to update Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkResponse</returns>
        public AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> SecurePaymentlinksIdPutWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'id' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'secureUpdatePaymentLinkRequest' is set
            if (secureUpdatePaymentLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'secureUpdatePaymentLinkRequest' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureUpdatePaymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksIdPut";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Put<PaymentLinkResponse>("/secure/paymentlinks/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksIdPut", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used to update Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkResponse</returns>
        public async System.Threading.Tasks.Task<PaymentLinkResponse> SecurePaymentlinksIdPutAsync(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> localVarResponse = await SecurePaymentlinksIdPutWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, id, secureUpdatePaymentLinkRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used to update Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="id">PaymentLink identifier</param>
        /// <param name="secureUpdatePaymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkResponse)</returns>
        public async System.Threading.Tasks.Task<AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse>> SecurePaymentlinksIdPutWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, string id, SecureUpdatePaymentLinkRequest secureUpdatePaymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'id' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }

            // verify the required parameter 'secureUpdatePaymentLinkRequest' is set
            if (secureUpdatePaymentLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'secureUpdatePaymentLinkRequest' when calling SecurePaymentLinksApi->SecurePaymentlinksIdPut");
            }


            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureUpdatePaymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksIdPut";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<PaymentLinkResponse>("/secure/paymentlinks/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksIdPut", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used to create Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaymentLinkResponse</returns>
        public PaymentLinkResponse SecurePaymentlinksPost(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0)
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> localVarResponse = SecurePaymentlinksPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, paymentLinkRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used to create Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaymentLinkResponse</returns>
        public AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> SecurePaymentlinksPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }

            // verify the required parameter 'paymentLinkRequest' is set
            if (paymentLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'paymentLinkRequest' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }

            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = paymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<PaymentLinkResponse>("/secure/paymentlinks", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used to create Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentLinkResponse</returns>
        public async System.Threading.Tasks.Task<PaymentLinkResponse> SecurePaymentlinksPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse> localVarResponse = await SecurePaymentlinksPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, paymentLinkRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used to create Payment Links 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="paymentLinkRequest">Payment Link Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentLinkResponse)</returns>
        public async System.Threading.Tasks.Task<AndDoneSecureClientLibrary.Client.ApiResponse<PaymentLinkResponse>> SecurePaymentlinksPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, PaymentLinkRequest paymentLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }

            // verify the required parameter 'paymentLinkRequest' is set
            if (paymentLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'paymentLinkRequest' when calling SecurePaymentLinksApi->SecurePaymentlinksPost");
            }


            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = paymentLinkRequest;

            localVarRequestOptions.Operation = "SecurePaymentLinksApi.SecurePaymentlinksPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PaymentLinkResponse>("/secure/paymentlinks", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecurePaymentlinksPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
