/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using AndDoneSecureClientLibrary.Client;
using AndDoneSecureClientLibrary.Model;

namespace AndDoneSecureClientLibrary.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureTokenManagementApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// This API is used for deactivating merchant token securely
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void SecureTokensActivationsDelete(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0);

        /// <summary>
        /// This API is used for deactivating merchant token securely
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> SecureTokensActivationsDeleteWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0);
        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link.
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SecureMerchantTokenShortResponse</returns>
        SecureMerchantTokenShortResponse SecureTokensDetailsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0);

        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SecureMerchantTokenShortResponse</returns>
        ApiResponse<SecureMerchantTokenShortResponse> SecureTokensDetailsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureTokenManagementApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// This API is used for deactivating merchant token securely
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task SecureTokensActivationsDeleteAsync(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used for deactivating merchant token securely
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SecureTokensActivationsDeleteWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SecureMerchantTokenShortResponse</returns>
        System.Threading.Tasks.Task<SecureMerchantTokenShortResponse> SecureTokensDetailsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SecureMerchantTokenShortResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SecureMerchantTokenShortResponse>> SecureTokensDetailsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureTokenManagementApi : ISecureTokenManagementApiSync, ISecureTokenManagementApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SecureTokenManagementApi : ISecureTokenManagementApi
    {
        private AndDoneSecureClientLibrary.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureTokenManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecureTokenManagementApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureTokenManagementApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecureTokenManagementApi(string basePath)
        {
            this.Configuration = AndDoneSecureClientLibrary.Client.Configuration.MergeConfigurations(
                AndDoneSecureClientLibrary.Client.GlobalConfiguration.Instance,
                new AndDoneSecureClientLibrary.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureTokenManagementApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SecureTokenManagementApi(AndDoneSecureClientLibrary.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AndDoneSecureClientLibrary.Client.Configuration.MergeConfigurations(
                AndDoneSecureClientLibrary.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AndDoneSecureClientLibrary.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureTokenManagementApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SecureTokenManagementApi(AndDoneSecureClientLibrary.Client.ISynchronousClient client, AndDoneSecureClientLibrary.Client.IAsynchronousClient asyncClient, AndDoneSecureClientLibrary.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AndDoneSecureClientLibrary.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AndDoneSecureClientLibrary.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AndDoneSecureClientLibrary.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// This API is used for deactivating merchant token securely 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void SecureTokensActivationsDelete(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0)
        {
            SecureTokensActivationsDeleteWithHttpInfo(xApiKey, xAppKey, xVersion, origin, tokenRequest);
        }

        /// <summary>
        /// This API is used for deactivating merchant token securely 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AndDoneSecureClientLibrary.Client.ApiResponse<Object> SecureTokensActivationsDeleteWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }

            // verify the required parameter 'tokenRequest' is set
            if (tokenRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'tokenRequest' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }

            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = tokenRequest;

            localVarRequestOptions.Operation = "SecureTokenManagementApi.SecureTokensActivationsDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/secure/tokens/activations", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureTokensActivationsDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for deactivating merchant token securely 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task SecureTokensActivationsDeleteAsync(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await SecureTokensActivationsDeleteWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, tokenRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// This API is used for deactivating merchant token securely 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="tokenRequest">secure merchant token request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AndDoneSecureClientLibrary.Client.ApiResponse<Object>> SecureTokensActivationsDeleteWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, TokenRequest tokenRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }

            // verify the required parameter 'tokenRequest' is set
            if (tokenRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'tokenRequest' when calling SecureTokenManagementApi->SecureTokensActivationsDelete");
            }


            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = tokenRequest;

            localVarRequestOptions.Operation = "SecureTokenManagementApi.SecureTokensActivationsDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/secure/tokens/activations", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureTokensActivationsDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SecureMerchantTokenShortResponse</returns>
        public SecureMerchantTokenShortResponse SecureTokensDetailsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0)
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<SecureMerchantTokenShortResponse> localVarResponse = SecureTokensDetailsPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, secureTokenLinkRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SecureMerchantTokenShortResponse</returns>
        public AndDoneSecureClientLibrary.Client.ApiResponse<SecureMerchantTokenShortResponse> SecureTokensDetailsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }

            // verify the required parameter 'secureTokenLinkRequest' is set
            if (secureTokenLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'secureTokenLinkRequest' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }

            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureTokenLinkRequest;

            localVarRequestOptions.Operation = "SecureTokenManagementApi.SecureTokensDetailsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<SecureMerchantTokenShortResponse>("/secure/tokens/details", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureTokensDetailsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SecureMerchantTokenShortResponse</returns>
        public async System.Threading.Tasks.Task<SecureMerchantTokenShortResponse> SecureTokensDetailsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            AndDoneSecureClientLibrary.Client.ApiResponse<SecureMerchantTokenShortResponse> localVarResponse = await SecureTokensDetailsPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, secureTokenLinkRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API is used for getting details of Merchant Token by Token link. 
        /// </summary>
        /// <exception cref="AndDoneSecureClientLibrary.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureTokenLinkRequest">Secure Token Link Id Request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SecureMerchantTokenShortResponse)</returns>
        public async System.Threading.Tasks.Task<AndDoneSecureClientLibrary.Client.ApiResponse<SecureMerchantTokenShortResponse>> SecureTokensDetailsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureTokenLinkRequest secureTokenLinkRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }

            // verify the required parameter 'secureTokenLinkRequest' is set
            if (secureTokenLinkRequest == null)
            {
                throw new AndDoneSecureClientLibrary.Client.ApiException(400, "Missing required parameter 'secureTokenLinkRequest' when calling SecureTokenManagementApi->SecureTokensDetailsPost");
            }


            AndDoneSecureClientLibrary.Client.RequestOptions localVarRequestOptions = new AndDoneSecureClientLibrary.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AndDoneSecureClientLibrary.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", AndDoneSecureClientLibrary.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureTokenLinkRequest;

            localVarRequestOptions.Operation = "SecureTokenManagementApi.SecureTokensDetailsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SecureMerchantTokenShortResponse>("/secure/tokens/details", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureTokensDetailsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
