/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using AndDoneSecureClientLibrary.Client;
using AndDoneSecureClientLibrary.Api;
// uncomment below to import models
//using AndDoneSecureClientLibrary.Model;

namespace AndDoneSecureClientLibrary.Test.Api
{
    /// <summary>
    ///  Class for testing SecureReportsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecureReportsApiTests : IDisposable
    {
        private SecureReportsApi instance;

        public SecureReportsApiTests()
        {
            instance = new SecureReportsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureReportsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecureReportsApi
            //Assert.IsType<SecureReportsApi>(instance);
        }

        /// <summary>
        /// Test SecureReportsDownloadsPost
        /// </summary>
        [Fact]
        public void SecureReportsDownloadsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //ReportDownloadRequest reportDownloadRequest = null;
            //instance.SecureReportsDownloadsPost(xApiKey, xAppKey, xVersion, origin, reportDownloadRequest);
        }
    }
}
