/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using AndDoneSecureClientLibrary.Client;
using AndDoneSecureClientLibrary.Api;
// uncomment below to import models
//using AndDoneSecureClientLibrary.Model;

namespace AndDoneSecureClientLibrary.Test.Api
{
    /// <summary>
    ///  Class for testing SecureOutboundPaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecureOutboundPaymentsApiTests : IDisposable
    {
        private SecureOutboundPaymentsApi instance;

        public SecureOutboundPaymentsApiTests()
        {
            instance = new SecureOutboundPaymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureOutboundPaymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecureOutboundPaymentsApi
            //Assert.IsType<SecureOutboundPaymentsApi>(instance);
        }

        /// <summary>
        /// Test VendorapiSecureOutboundPaymentsTimelinesPost
        /// </summary>
        [Fact]
        public void VendorapiSecureOutboundPaymentsTimelinesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //PaymentTimeLineRequestDto paymentTimeLineRequestDto = null;
            //var response = instance.VendorapiSecureOutboundPaymentsTimelinesPost(xApiKey, xAppKey, xVersion, origin, paymentTimeLineRequestDto);
            //Assert.IsType<List<OutboundPaymentTimelineResponseDTOInner>>(response);
        }

        /// <summary>
        /// Test VendorapiSecureOutboundpaymentsCancelPost
        /// </summary>
        [Fact]
        public void VendorapiSecureOutboundpaymentsCancelPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //CancelPaymentRequestDTO cancelPaymentRequestDTO = null;
            //instance.VendorapiSecureOutboundpaymentsCancelPost(xApiKey, xAppKey, xVersion, origin, cancelPaymentRequestDTO);
        }

        /// <summary>
        /// Test VendorapiSecureOutboundpaymentsDetailPost
        /// </summary>
        [Fact]
        public void VendorapiSecureOutboundpaymentsDetailPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //PaymentRequestDetailDTO paymentRequestDetailDTO = null;
            //var response = instance.VendorapiSecureOutboundpaymentsDetailPost(xApiKey, xAppKey, xVersion, origin, paymentRequestDetailDTO);
            //Assert.IsType<PaymentDetailResponseDTO>(response);
        }

        /// <summary>
        /// Test VendorapiSecureOutboundpaymentsImagePost
        /// </summary>
        [Fact]
        public void VendorapiSecureOutboundpaymentsImagePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //PaymentTimeLineRequestDto paymentTimeLineRequestDto = null;
            //var response = instance.VendorapiSecureOutboundpaymentsImagePost(xApiKey, xAppKey, xVersion, origin, paymentTimeLineRequestDto);
            //Assert.IsType<OutboundPaymentImageResponseDTO>(response);
        }

        /// <summary>
        /// Test VendorapiSecureOutboundpaymentsPost
        /// </summary>
        [Fact]
        public void VendorapiSecureOutboundpaymentsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //PaymentRequestDto paymentRequestDto = null;
            //var response = instance.VendorapiSecureOutboundpaymentsPost(xApiKey, xAppKey, xVersion, origin, paymentRequestDto);
            //Assert.IsType<PaymentResponseDto>(response);
        }

        /// <summary>
        /// Test VendorapiSecureOutboundpaymentsSearchPost
        /// </summary>
        [Fact]
        public void VendorapiSecureOutboundpaymentsSearchPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //string vendorId = null;
            //string paymentBasedId = null;
            //string paymentId = null;
            //string vendorName = null;
            //string paymentMethodType = null;
            //string paymentMethodStatus = null;
            //float? amount = null;
            //float? fromAmount = null;
            //float? toAmount = null;
            //string startDate = null;
            //string endDate = null;
            //string searchText = null;
            //int? startRow = null;
            //int? pageSize = null;
            //string sortField = null;
            //bool? asc = null;
            //var response = instance.VendorapiSecureOutboundpaymentsSearchPost(xApiKey, xAppKey, xVersion, origin, vendorId, paymentBasedId, paymentId, vendorName, paymentMethodType, paymentMethodStatus, amount, fromAmount, toAmount, startDate, endDate, searchText, startRow, pageSize, sortField, asc);
            //Assert.IsType<PagePaymentListResponseDTO>(response);
        }
    }
}
