/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AndDoneSecureClientLibrary.Model;
using AndDoneSecureClientLibrary.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AndDoneSecureClientLibrary.Test.Model
{
    /// <summary>
    ///  Class for testing AutoPayEnrollmentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutoPayEnrollmentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutoPayEnrollmentResponse
        //private AutoPayEnrollmentResponse instance;

        public AutoPayEnrollmentResponseTests()
        {
            // TODO uncomment below to create an instance of AutoPayEnrollmentResponse
            //instance = new AutoPayEnrollmentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutoPayEnrollmentResponse
        /// </summary>
        [Fact]
        public void AutoPayEnrollmentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutoPayEnrollmentResponse
            //Assert.IsType<AutoPayEnrollmentResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'IsSuccess'
        /// </summary>
        [Fact]
        public void IsSuccessTest()
        {
            // TODO unit test for the property 'IsSuccess'
        }

        /// <summary>
        /// Test the property 'IntegrationID'
        /// </summary>
        [Fact]
        public void IntegrationIDTest()
        {
            // TODO unit test for the property 'IntegrationID'
        }
    }
}
