/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AndDoneSecureClientLibrary.Model;
using AndDoneSecureClientLibrary.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AndDoneSecureClientLibrary.Test.Model
{
    /// <summary>
    ///  Class for testing PFLiteSecureQuoteRequestAgent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PFLiteSecureQuoteRequestAgentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PFLiteSecureQuoteRequestAgent
        //private PFLiteSecureQuoteRequestAgent instance;

        public PFLiteSecureQuoteRequestAgentTests()
        {
            // TODO uncomment below to create an instance of PFLiteSecureQuoteRequestAgent
            //instance = new PFLiteSecureQuoteRequestAgent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PFLiteSecureQuoteRequestAgent
        /// </summary>
        [Fact]
        public void PFLiteSecureQuoteRequestAgentInstanceTest()
        {
            // TODO uncomment below to test "IsType" PFLiteSecureQuoteRequestAgent
            //Assert.IsType<PFLiteSecureQuoteRequestAgent>(instance);
        }

        /// <summary>
        /// Test the property 'UniqueID'
        /// </summary>
        [Fact]
        public void UniqueIDTest()
        {
            // TODO unit test for the property 'UniqueID'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'CareOf'
        /// </summary>
        [Fact]
        public void CareOfTest()
        {
            // TODO unit test for the property 'CareOf'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
    }
}
