/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AndDoneSecureClientLibrary.Model;
using AndDoneSecureClientLibrary.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AndDoneSecureClientLibrary.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionPaymentResponseAchTenderInfoCommissionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionPaymentResponseAchTenderInfoCommissionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionPaymentResponseAchTenderInfoCommissionType
        //private TransactionPaymentResponseAchTenderInfoCommissionType instance;

        public TransactionPaymentResponseAchTenderInfoCommissionTypeTests()
        {
            // TODO uncomment below to create an instance of TransactionPaymentResponseAchTenderInfoCommissionType
            //instance = new TransactionPaymentResponseAchTenderInfoCommissionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionPaymentResponseAchTenderInfoCommissionType
        /// </summary>
        [Fact]
        public void TransactionPaymentResponseAchTenderInfoCommissionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionPaymentResponseAchTenderInfoCommissionType
            //Assert.IsType<TransactionPaymentResponseAchTenderInfoCommissionType>(instance);
        }
    }
}
