/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureACHValidationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// This API verifies bank account using secure ACH validation
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>VerifyBankAccountResponse</returns>
        VerifyBankAccountResponse UtilityapiSecureVerifybankaccountsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0);

        /// <summary>
        /// This API verifies bank account using secure ACH validation
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of VerifyBankAccountResponse</returns>
        ApiResponse<VerifyBankAccountResponse> UtilityapiSecureVerifybankaccountsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureACHValidationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// This API verifies bank account using secure ACH validation
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of VerifyBankAccountResponse</returns>
        System.Threading.Tasks.Task<VerifyBankAccountResponse> UtilityapiSecureVerifybankaccountsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// This API verifies bank account using secure ACH validation
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (VerifyBankAccountResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<VerifyBankAccountResponse>> UtilityapiSecureVerifybankaccountsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISecureACHValidationApi : ISecureACHValidationApiSync, ISecureACHValidationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SecureACHValidationApi : ISecureACHValidationApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureACHValidationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecureACHValidationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureACHValidationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SecureACHValidationApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureACHValidationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SecureACHValidationApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecureACHValidationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SecureACHValidationApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// This API verifies bank account using secure ACH validation 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>VerifyBankAccountResponse</returns>
        public VerifyBankAccountResponse UtilityapiSecureVerifybankaccountsPost(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<VerifyBankAccountResponse> localVarResponse = UtilityapiSecureVerifybankaccountsPostWithHttpInfo(xApiKey, xAppKey, xVersion, origin, secureVerifyBankAccountRequestDTO);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API verifies bank account using secure ACH validation 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of VerifyBankAccountResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<VerifyBankAccountResponse> UtilityapiSecureVerifybankaccountsPostWithHttpInfo(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0)
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }

            // verify the required parameter 'secureVerifyBankAccountRequestDTO' is set
            if (secureVerifyBankAccountRequestDTO == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'secureVerifyBankAccountRequestDTO' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureVerifyBankAccountRequestDTO;

            localVarRequestOptions.Operation = "SecureACHValidationApi.UtilityapiSecureVerifybankaccountsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<VerifyBankAccountResponse>("/utilityapi/secure/verifybankaccounts", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UtilityapiSecureVerifybankaccountsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This API verifies bank account using secure ACH validation 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of VerifyBankAccountResponse</returns>
        public async System.Threading.Tasks.Task<VerifyBankAccountResponse> UtilityapiSecureVerifybankaccountsPostAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<VerifyBankAccountResponse> localVarResponse = await UtilityapiSecureVerifybankaccountsPostWithHttpInfoAsync(xApiKey, xAppKey, xVersion, origin, secureVerifyBankAccountRequestDTO, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This API verifies bank account using secure ACH validation 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xApiKey">an authorization header</param>
        /// <param name="xAppKey">an authorization header</param>
        /// <param name="xVersion">x-version</param>
        /// <param name="origin">origin</param>
        /// <param name="secureVerifyBankAccountRequestDTO">SecureVerifyBankAccountRequestDTO</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (VerifyBankAccountResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<VerifyBankAccountResponse>> UtilityapiSecureVerifybankaccountsPostWithHttpInfoAsync(string xApiKey, string xAppKey, float xVersion, string origin, SecureVerifyBankAccountRequestDTO secureVerifyBankAccountRequestDTO, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'xApiKey' is set
            if (xApiKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xApiKey' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }

            // verify the required parameter 'xAppKey' is set
            if (xAppKey == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'xAppKey' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }

            // verify the required parameter 'origin' is set
            if (origin == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'origin' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }

            // verify the required parameter 'secureVerifyBankAccountRequestDTO' is set
            if (secureVerifyBankAccountRequestDTO == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'secureVerifyBankAccountRequestDTO' when calling SecureACHValidationApi->UtilityapiSecureVerifybankaccountsPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("x-api-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xApiKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-app-key", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xAppKey)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("x-version", Org.OpenAPITools.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            localVarRequestOptions.HeaderParameters.Add("origin", Org.OpenAPITools.Client.ClientUtils.ParameterToString(origin)); // header parameter
            localVarRequestOptions.Data = secureVerifyBankAccountRequestDTO;

            localVarRequestOptions.Operation = "SecureACHValidationApi.UtilityapiSecureVerifybankaccountsPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<VerifyBankAccountResponse>("/utilityapi/secure/verifybankaccounts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UtilityapiSecureVerifybankaccountsPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
