/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SecurePaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SecurePaymentsApiTests : IDisposable
    {
        private SecurePaymentsApi instance;

        public SecurePaymentsApiTests()
        {
            instance = new SecurePaymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecurePaymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SecurePaymentsApi
            //Assert.IsType<SecurePaymentsApi>(instance);
        }

        /// <summary>
        /// Test SecurePaymentsExportPost
        /// </summary>
        [Fact]
        public void SecurePaymentsExportPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //string startDate = null;
            //string endDate = null;
            //string transactionIds = null;
            //string referenceTransactionId = null;
            //string transactionStatuses = null;
            //string customerIds = null;
            //string transactionType = null;
            //string authCode = null;
            //string cardHolderName = null;
            //string shopperName = null;
            //float? amount = null;
            //float? fromAmount = null;
            //float? toAmount = null;
            //string channelTypes = null;
            //string maskAccount = null;
            //string customerName = null;
            //string recurringId = null;
            //string referenceNo = null;
            //bool? exportToCsv = null;
            //bool? exportToPDF = null;
            //string transactionOrigins = null;
            //string transactionSourceType = null;
            //float? sourceId = null;
            //string traceNumbers = null;
            //string binNumber = null;
            //string processMethod = null;
            //string searchText = null;
            //string merchantReference = null;
            //string additionalFields = null;
            //string additionalFieldValue = null;
            //string paymentMethod = null;
            //string accountAlias = null;
            //bool? isPaid = null;
            //string paymentTypes = null;
            //string merchantId = null;
            //string paymentCategories = null;
            //bool? suppressTechnologyFee = null;
            //string batchId = null;
            //string sortField = null;
            //float? startRow = null;
            //float? pageSize = null;
            //bool? asc = null;
            //instance.SecurePaymentsExportPost(xApiKey, xAppKey, xVersion, origin, startDate, endDate, transactionIds, referenceTransactionId, transactionStatuses, customerIds, transactionType, authCode, cardHolderName, shopperName, amount, fromAmount, toAmount, channelTypes, maskAccount, customerName, recurringId, referenceNo, exportToCsv, exportToPDF, transactionOrigins, transactionSourceType, sourceId, traceNumbers, binNumber, processMethod, searchText, merchantReference, additionalFields, additionalFieldValue, paymentMethod, accountAlias, isPaid, paymentTypes, merchantId, paymentCategories, suppressTechnologyFee, batchId, sortField, startRow, pageSize, asc);
        }

        /// <summary>
        /// Test SecurePaymentsPost
        /// </summary>
        [Fact]
        public void SecurePaymentsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //PaymentRequest paymentRequest = null;
            //var response = instance.SecurePaymentsPost(xApiKey, xAppKey, xVersion, origin, paymentRequest);
            //Assert.IsType<TransactionDetailResponse>(response);
        }

        /// <summary>
        /// Test SecurePaymentsSearchPost
        /// </summary>
        [Fact]
        public void SecurePaymentsSearchPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //string startDate = null;
            //string endDate = null;
            //string transactionIds = null;
            //string referenceTransactionId = null;
            //string transactionStatuses = null;
            //string customerIds = null;
            //string transactionType = null;
            //string authCode = null;
            //string cardHolderName = null;
            //string shopperName = null;
            //float? amount = null;
            //float? fromAmount = null;
            //float? toAmount = null;
            //string channelTypes = null;
            //string maskAccount = null;
            //string customerName = null;
            //string recurringId = null;
            //string referenceNo = null;
            //bool? exportToCsv = null;
            //bool? exportToPDF = null;
            //string transactionOrigins = null;
            //string transactionSourceType = null;
            //float? sourceId = null;
            //string traceNumbers = null;
            //string binNumber = null;
            //string processMethod = null;
            //string searchText = null;
            //string merchantReference = null;
            //string additionalFields = null;
            //string additionalFieldValue = null;
            //string paymentMethod = null;
            //string accountAlias = null;
            //bool? isPaid = null;
            //string paymentTypes = null;
            //string merchantId = null;
            //string paymentCategories = null;
            //bool? suppressTechnologyFee = null;
            //string batchId = null;
            //string sortField = null;
            //float? startRow = null;
            //float? pageSize = null;
            //bool? asc = null;
            //var response = instance.SecurePaymentsSearchPost(xApiKey, xAppKey, xVersion, origin, startDate, endDate, transactionIds, referenceTransactionId, transactionStatuses, customerIds, transactionType, authCode, cardHolderName, shopperName, amount, fromAmount, toAmount, channelTypes, maskAccount, customerName, recurringId, referenceNo, exportToCsv, exportToPDF, transactionOrigins, transactionSourceType, sourceId, traceNumbers, binNumber, processMethod, searchText, merchantReference, additionalFields, additionalFieldValue, paymentMethod, accountAlias, isPaid, paymentTypes, merchantId, paymentCategories, suppressTechnologyFee, batchId, sortField, startRow, pageSize, asc);
            //Assert.IsType<MerchantTransactionEntityResponse>(response);
        }

        /// <summary>
        /// Test SecurePaymentsdetailsPost
        /// </summary>
        [Fact]
        public void SecurePaymentsdetailsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiKey = null;
            //string xAppKey = null;
            //float xVersion = null;
            //string origin = null;
            //SecurePaymentDetailsRequest securePaymentDetailsRequest = null;
            //var response = instance.SecurePaymentsdetailsPost(xApiKey, xAppKey, xVersion, origin, securePaymentDetailsRequest);
            //Assert.IsType<TransactionPaymentResponse>(response);
        }
    }
}
