/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = AndDoneSecureClientLibrary.Client.OpenAPIDateConverter;

namespace AndDoneSecureClientLibrary.Model
{
    /// <summary>
    /// AutoPayEnrollmentRequest
    /// </summary>
    [DataContract(Name = "AutoPayEnrollmentRequest")]
    public partial class AutoPayEnrollmentRequest : IValidatableObject
    {
        /// <summary>
        /// Defines ProcessMethod
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProcessMethodEnum
        {
            /// <summary>
            /// Enum NotDefined for value: NotDefined
            /// </summary>
            [EnumMember(Value = "NotDefined")]
            NotDefined = 1,

            /// <summary>
            /// Enum ACH for value: ACH
            /// </summary>
            [EnumMember(Value = "ACH")]
            ACH = 2,

            /// <summary>
            /// Enum CardNotPresent for value: CardNotPresent
            /// </summary>
            [EnumMember(Value = "CardNotPresent")]
            CardNotPresent = 3
        }


        /// <summary>
        /// Gets or Sets ProcessMethod
        /// </summary>
        [DataMember(Name = "processMethod", IsRequired = true, EmitDefaultValue = true)]
        public ProcessMethodEnum ProcessMethod { get; set; }
        /// <summary>
        /// Defines ChannelType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ChannelTypeEnum
        {
            /// <summary>
            /// Enum NotDefined for value: NotDefined
            /// </summary>
            [EnumMember(Value = "NotDefined")]
            NotDefined = 1,

            /// <summary>
            /// Enum ACH for value: ACH
            /// </summary>
            [EnumMember(Value = "ACH")]
            ACH = 2,

            /// <summary>
            /// Enum CreditCard for value: CreditCard
            /// </summary>
            [EnumMember(Value = "CreditCard")]
            CreditCard = 3,

            /// <summary>
            /// Enum DebitCard for value: DebitCard
            /// </summary>
            [EnumMember(Value = "DebitCard")]
            DebitCard = 4,

            /// <summary>
            /// Enum RTP for value: RTP
            /// </summary>
            [EnumMember(Value = "RTP")]
            RTP = 5
        }


        /// <summary>
        /// Gets or Sets ChannelType
        /// </summary>
        [DataMember(Name = "channelType", EmitDefaultValue = false)]
        public ChannelTypeEnum? ChannelType { get; set; }
        /// <summary>
        /// Defines AccountType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AccountTypeEnum
        {
            /// <summary>
            /// Enum Checking for value: checking
            /// </summary>
            [EnumMember(Value = "checking")]
            Checking = 1,

            /// <summary>
            /// Enum Savings for value: savings
            /// </summary>
            [EnumMember(Value = "savings")]
            Savings = 2
        }


        /// <summary>
        /// Gets or Sets AccountType
        /// </summary>
        [DataMember(Name = "accountType", EmitDefaultValue = false)]
        public AccountTypeEnum? AccountType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AutoPayEnrollmentRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AutoPayEnrollmentRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AutoPayEnrollmentRequest" /> class.
        /// </summary>
        /// <param name="merchantId">merchantId.</param>
        /// <param name="quoteKey">quoteKey (required).</param>
        /// <param name="paymentIntentId">paymentIntentId (required).</param>
        /// <param name="emailAddress">emailAddress (required).</param>
        /// <param name="processMethod">processMethod (required).</param>
        /// <param name="creditCardToken">creditCardToken.</param>
        /// <param name="channelType">channelType.</param>
        /// <param name="cardholderName">cardholderName.</param>
        /// <param name="adyenPSP">adyenPSP.</param>
        /// <param name="accountOwnerName">accountOwnerName.</param>
        /// <param name="bankRoutingNumber">bankRoutingNumber.</param>
        /// <param name="bankAccountNumber">bankAccountNumber.</param>
        /// <param name="accountType">accountType.</param>
        public AutoPayEnrollmentRequest(string merchantId = default(string), string quoteKey = default(string), string paymentIntentId = default(string), string emailAddress = default(string), ProcessMethodEnum processMethod = default(ProcessMethodEnum), string creditCardToken = default(string), ChannelTypeEnum? channelType = default(ChannelTypeEnum?), string cardholderName = default(string), string adyenPSP = default(string), string accountOwnerName = default(string), string bankRoutingNumber = default(string), string bankAccountNumber = default(string), AccountTypeEnum? accountType = default(AccountTypeEnum?))
        {
            // to ensure "quoteKey" is required (not null)
            if (quoteKey == null)
            {
                throw new ArgumentNullException("quoteKey is a required property for AutoPayEnrollmentRequest and cannot be null");
            }
            this.QuoteKey = quoteKey;
            // to ensure "paymentIntentId" is required (not null)
            if (paymentIntentId == null)
            {
                throw new ArgumentNullException("paymentIntentId is a required property for AutoPayEnrollmentRequest and cannot be null");
            }
            this.PaymentIntentId = paymentIntentId;
            // to ensure "emailAddress" is required (not null)
            if (emailAddress == null)
            {
                throw new ArgumentNullException("emailAddress is a required property for AutoPayEnrollmentRequest and cannot be null");
            }
            this.EmailAddress = emailAddress;
            this.ProcessMethod = processMethod;
            this.MerchantId = merchantId;
            this.CreditCardToken = creditCardToken;
            this.ChannelType = channelType;
            this.CardholderName = cardholderName;
            this.AdyenPSP = adyenPSP;
            this.AccountOwnerName = accountOwnerName;
            this.BankRoutingNumber = bankRoutingNumber;
            this.BankAccountNumber = bankAccountNumber;
            this.AccountType = accountType;
        }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name = "merchantId", EmitDefaultValue = false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets QuoteKey
        /// </summary>
        [DataMember(Name = "Quote Key", IsRequired = true, EmitDefaultValue = true)]
        public string QuoteKey { get; set; }

        /// <summary>
        /// Gets or Sets PaymentIntentId
        /// </summary>
        [DataMember(Name = "paymentIntentId", IsRequired = true, EmitDefaultValue = true)]
        public string PaymentIntentId { get; set; }

        /// <summary>
        /// Gets or Sets EmailAddress
        /// </summary>
        [DataMember(Name = "emailAddress", IsRequired = true, EmitDefaultValue = true)]
        public string EmailAddress { get; set; }

        /// <summary>
        /// Gets or Sets CreditCardToken
        /// </summary>
        [DataMember(Name = "creditCardToken", EmitDefaultValue = false)]
        public string CreditCardToken { get; set; }

        /// <summary>
        /// Gets or Sets CardholderName
        /// </summary>
        [DataMember(Name = "cardholderName", EmitDefaultValue = false)]
        public string CardholderName { get; set; }

        /// <summary>
        /// Gets or Sets AdyenPSP
        /// </summary>
        [DataMember(Name = "adyenPSP", EmitDefaultValue = false)]
        public string AdyenPSP { get; set; }

        /// <summary>
        /// Gets or Sets AccountOwnerName
        /// </summary>
        [DataMember(Name = "accountOwnerName", EmitDefaultValue = false)]
        public string AccountOwnerName { get; set; }

        /// <summary>
        /// Gets or Sets BankRoutingNumber
        /// </summary>
        [DataMember(Name = "bankRoutingNumber", EmitDefaultValue = false)]
        public string BankRoutingNumber { get; set; }

        /// <summary>
        /// Gets or Sets BankAccountNumber
        /// </summary>
        [DataMember(Name = "bankAccountNumber", EmitDefaultValue = false)]
        public string BankAccountNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutoPayEnrollmentRequest {\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  QuoteKey: ").Append(QuoteKey).Append("\n");
            sb.Append("  PaymentIntentId: ").Append(PaymentIntentId).Append("\n");
            sb.Append("  EmailAddress: ").Append(EmailAddress).Append("\n");
            sb.Append("  ProcessMethod: ").Append(ProcessMethod).Append("\n");
            sb.Append("  CreditCardToken: ").Append(CreditCardToken).Append("\n");
            sb.Append("  ChannelType: ").Append(ChannelType).Append("\n");
            sb.Append("  CardholderName: ").Append(CardholderName).Append("\n");
            sb.Append("  AdyenPSP: ").Append(AdyenPSP).Append("\n");
            sb.Append("  AccountOwnerName: ").Append(AccountOwnerName).Append("\n");
            sb.Append("  BankRoutingNumber: ").Append(BankRoutingNumber).Append("\n");
            sb.Append("  BankAccountNumber: ").Append(BankAccountNumber).Append("\n");
            sb.Append("  AccountType: ").Append(AccountType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
