/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AutoPayEnrollmentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutoPayEnrollmentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutoPayEnrollmentRequest
        //private AutoPayEnrollmentRequest instance;

        public AutoPayEnrollmentRequestTests()
        {
            // TODO uncomment below to create an instance of AutoPayEnrollmentRequest
            //instance = new AutoPayEnrollmentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutoPayEnrollmentRequest
        /// </summary>
        [Fact]
        public void AutoPayEnrollmentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutoPayEnrollmentRequest
            //Assert.IsType<AutoPayEnrollmentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Fact]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }

        /// <summary>
        /// Test the property 'QuoteKey'
        /// </summary>
        [Fact]
        public void QuoteKeyTest()
        {
            // TODO unit test for the property 'QuoteKey'
        }

        /// <summary>
        /// Test the property 'PaymentIntentId'
        /// </summary>
        [Fact]
        public void PaymentIntentIdTest()
        {
            // TODO unit test for the property 'PaymentIntentId'
        }

        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }

        /// <summary>
        /// Test the property 'ProcessMethod'
        /// </summary>
        [Fact]
        public void ProcessMethodTest()
        {
            // TODO unit test for the property 'ProcessMethod'
        }

        /// <summary>
        /// Test the property 'CreditCardToken'
        /// </summary>
        [Fact]
        public void CreditCardTokenTest()
        {
            // TODO unit test for the property 'CreditCardToken'
        }

        /// <summary>
        /// Test the property 'ChannelType'
        /// </summary>
        [Fact]
        public void ChannelTypeTest()
        {
            // TODO unit test for the property 'ChannelType'
        }

        /// <summary>
        /// Test the property 'CardholderName'
        /// </summary>
        [Fact]
        public void CardholderNameTest()
        {
            // TODO unit test for the property 'CardholderName'
        }

        /// <summary>
        /// Test the property 'AdyenPSP'
        /// </summary>
        [Fact]
        public void AdyenPSPTest()
        {
            // TODO unit test for the property 'AdyenPSP'
        }

        /// <summary>
        /// Test the property 'AccountOwnerName'
        /// </summary>
        [Fact]
        public void AccountOwnerNameTest()
        {
            // TODO unit test for the property 'AccountOwnerName'
        }

        /// <summary>
        /// Test the property 'BankRoutingNumber'
        /// </summary>
        [Fact]
        public void BankRoutingNumberTest()
        {
            // TODO unit test for the property 'BankRoutingNumber'
        }

        /// <summary>
        /// Test the property 'BankAccountNumber'
        /// </summary>
        [Fact]
        public void BankAccountNumberTest()
        {
            // TODO unit test for the property 'BankAccountNumber'
        }

        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
    }
}
