/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OutboundPaymentImageResponseDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutboundPaymentImageResponseDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutboundPaymentImageResponseDTO
        //private OutboundPaymentImageResponseDTO instance;

        public OutboundPaymentImageResponseDTOTests()
        {
            // TODO uncomment below to create an instance of OutboundPaymentImageResponseDTO
            //instance = new OutboundPaymentImageResponseDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutboundPaymentImageResponseDTO
        /// </summary>
        [Fact]
        public void OutboundPaymentImageResponseDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutboundPaymentImageResponseDTO
            //Assert.IsType<OutboundPaymentImageResponseDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
    }
}
