/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SecureVerifyBankAccountRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecureVerifyBankAccountRequestDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecureVerifyBankAccountRequestDTO
        //private SecureVerifyBankAccountRequestDTO instance;

        public SecureVerifyBankAccountRequestDTOTests()
        {
            // TODO uncomment below to create an instance of SecureVerifyBankAccountRequestDTO
            //instance = new SecureVerifyBankAccountRequestDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecureVerifyBankAccountRequestDTO
        /// </summary>
        [Fact]
        public void SecureVerifyBankAccountRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecureVerifyBankAccountRequestDTO
            //Assert.IsType<SecureVerifyBankAccountRequestDTO>(instance);
        }

        /// <summary>
        /// Test the property 'VerificationEntityId'
        /// </summary>
        [Fact]
        public void VerificationEntityIdTest()
        {
            // TODO unit test for the property 'VerificationEntityId'
        }

        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }

        /// <summary>
        /// Test the property 'RoutingNumber'
        /// </summary>
        [Fact]
        public void RoutingNumberTest()
        {
            // TODO unit test for the property 'RoutingNumber'
        }

        /// <summary>
        /// Test the property 'AccountHolderName'
        /// </summary>
        [Fact]
        public void AccountHolderNameTest()
        {
            // TODO unit test for the property 'AccountHolderName'
        }

        /// <summary>
        /// Test the property 'ExplicitVerification'
        /// </summary>
        [Fact]
        public void ExplicitVerificationTest()
        {
            // TODO unit test for the property 'ExplicitVerification'
        }
    }
}
