/*
 * Secure API
 *
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionPaymentResponseRefundOrigin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionPaymentResponseRefundOriginTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionPaymentResponseRefundOrigin
        //private TransactionPaymentResponseRefundOrigin instance;

        public TransactionPaymentResponseRefundOriginTests()
        {
            // TODO uncomment below to create an instance of TransactionPaymentResponseRefundOrigin
            //instance = new TransactionPaymentResponseRefundOrigin();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionPaymentResponseRefundOrigin
        /// </summary>
        [Fact]
        public void TransactionPaymentResponseRefundOriginInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionPaymentResponseRefundOrigin
            //Assert.IsType<TransactionPaymentResponseRefundOrigin>(instance);
        }
    }
}
